global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["0.0.0.0:9091"]

  - job_name: "node"
    static_configs:
    - targets: ["0.0.0.0:9101"]

  - job_name: "online_serving"
    scrape_interval: 5s
    static_configs:
    - targets: ["0.0.0.0:8172"]

  - job_name: "monitoring_service"
    scrape_interval: 5s
    static_configs:
    - targets: ["0.0.0.0:8309"]
